Add html css and JS files
JoyTaribagshaw/ES6-AwesomeBooks-Project pull request #1
Opened 2023-07-11 18:28 UTC by JoyTaribagshaw

**highlight**

2023-07-11 23:01 UTC, shahadat3669 requested changes
Hi @JoyTaribagshaw , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
✅ Good UI
✅ Cleane Code
✅ No linter Errors 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 23:01 UTC, shahadat3669 commented on script.js
- [ ] 🌟 Your main JavaScript file name is `script.js`, but as per the project requirement, the main file should be named `index.html`. Please consider renaming your main JavaScript file to `index.html` to adhere to the project guidelines.
![image](https://github.com/JoyTaribagshaw/ES6-AwesomeBooks-Project/assets/55840999/5ddd00f1-87e0-41cd-a777-08412a80e652)
Great job on your progress so far, and keep up the good work! 👍

2023-07-11 23:01 UTC, shahadat3669 commented on script.js
> +}
- [ ] 📦 I recommend organizing your code by creating a separate file for the `BookStore` class. You can save it in the `modules` folder and then import it in your main JavaScript file, `index.js`, to utilize the class. This will improve code organization and maintainability. Keep up the great work and make sure to implement this suggestion for better code structure! 👍

2023-07-12 08:30 UTC, JoyTaribagshaw commented on script.js
Thank you so much for your review @shahadat3669 , I have made the changes.

![index js](https://github.com/JoyTaribagshaw/ES6-AwesomeBooks-Project/assets/111312788/bb44bc70-e101-4218-8102-11f5de5dc4f7)

2023-07-12 08:30 UTC, JoyTaribagshaw commented on script.js
> +}
Thank you so much for your review @shahadat3669 , I have organized my code by creating a separate file for the BookStore class.
![bookstore-module](https://github.com/JoyTaribagshaw/ES6-AwesomeBooks-Project/assets/111312788/6d708170-f5f8-4be0-98bd-60fd315c331f)

2023-07-12 08:45 UTC, wayungi approved these changes
Hi @JoyTaribagshaw , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] luxon library properly used ✔️ 
- [ ] Arrow functions well used ✔️ 
- [ ] Code is split into modules ✔️ 
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 08:48 UTC, merged